### ISSUE TITLE
wlan可以使用itlwm.kext配合HeliPort，蓝牙显示打开，但搜不到信号

### ISSUE THREAD

**Issue by cgjue** [ThrRip/OpenCore-EFI-AsRock-H410M-ITX-AC-i3-10100#1]
wlan可以使用itlwm.kext配合HeliPort，蓝牙显示打开，但搜不到信号

**Comment by ThrRip** [comment]
您好，

我们已收到您的建议和问题！

WLAN其实有比你说的更好的方法，请参考 [openintelwireless.github.io/itlwm/Installation.html](https://openintelwireless.github.io/itlwm/Installation.html#airportitlwm)。

另外，其实本项目是源于 ThrRip 为他人远程 Hackintosh 时配置的 EFI 文件，因为时间关系就没有继续维护。

稍后我将会再更新一下此项目，确保能适配更新的操作系统，且修复WLAN和蓝牙的问题。

感谢您对 ThrRip 的支持！如果此项目帮助到了您，可以选择给出 Star 并 Follow 我。

敬上

**Comment by ThrRip** [comment]
您好，我已经发布了可以成功驱动无线网卡和蓝牙的新版本 EFI 文件。

查看[这里](https://github.com/ThrRip/OpenCore-EFI-AsRock-H410M-ITX-AC-i3-10100/releases/tag/1.1.0)以了解详情。
