### ISSUE TITLE
没有第一版好用，开机无法启动，貌似是load configure failed

### ISSUE THREAD

**Issue by cgjue** [ThrRip/OpenCore-EFI-AsRock-H410M-ITX-AC-i3-10100#2]
没有第一版好用，开机无法启动，貌似是load configure failed

**Comment by ThrRip** [comment]
此项目并不是 ThrRip 在主要维护的项目，ThrRip 也没有此配置的设备以供测试，所以如果您在使用中出现了问题，请自行修复。
